<?php

namespace App\Constants;

class ErrorCode
{
    const HOLIDAY = 'ATTENDANCE_HOLIDAY';
    const WEEKEND = 'ATTENDANCE_WEEKEND';
    const TOO_EARLY = 'ATTENDANCE_TOO_EARLY';
    const TOO_LATE = 'ATTENDANCE_TOO_LATE';
    const NOT_TIME_YET = 'ATTENDANCE_NOT_TIME_YET';
    const SCHEDULE_NOT_FOUND = 'SCHEDULE_NOT_FOUND';
    const ALREADY_CLOCKED_IN = 'ATTENDANCE_ALREADY_CLOCKED_IN';
    const WORKDAY_NOT_CONFIGURED = 'WORKDAY_NOT_CONFIGURED';
    const TPP_CONFIG_NOT_FOUND = 'ATTENDANCE_TPP_CONFIG_NOT_FOUND';
    const NOT_CLOCKED_IN = 'ATTENDANCE_NOT_CLOCKED_IN';
    const ALREADY_CLOCKED_OUT = 'ATTENDANCE_ALREADY_CLOCKED_OUT';
    const APEL_NOT_SCHEDULED = 'ATTENDANCE_APEL_NOT_SCHEDULED';
    const APEL_TOO_EARLY = 'ATTENDANCE_APEL_TOO_EARLY';
    const APEL_TOO_LATE = 'ATTENDANCE_APEL_TOO_LATE';
    const APEL_ALREADY = 'ATTENDANCE_APEL_ALREADY';
}